import type { RecordKey } from '../types/object.type';
import { entries } from './entries';
import { fromEntries } from './from-entries';

/**
 * Iteratee Type.
 * @param entry An `object` entry, which is a key-value pair.
 * @template Key Type for the entry's `key` passed in params.
 * @template Value Type for the entry's `value` passed in params.
 * @template TransformedResult Return type of the iteratee. Must be an array of 2 elements [key, value].
 * @returns The transformation of the `entry` in the same shape (key-value pair).
 */
export type Iteratee<
  Key extends RecordKey,
  Value,
  TransformedResult extends [RecordKey, unknown],
> = (entry: [Key, Value]) => TransformedResult;

/**
 * Creates an object with entries generated by running each own enumerable entry of object through iteratee. The iteratee is invoked with a tuple argument: [key, value].
 * @param object The object to iterate over.
 * @param iteratee The function invoked per iteration.
 * @template Key Type of the keys that composed the `object`.
 * @template Value Type of the values that composed the `object`.
 * @template TransformedKey Type of the transformation apply to the keys that composed the `object`.
 * @template TransformedValue Type of the transformation apply to the values that composed the `object`.
 * @returns Returns the new mapped object.
 */
export const map = <
  Key extends RecordKey,
  Value,
  TransformedKey extends RecordKey,
  TransformedValue,
>(
  object: Readonly<Record<Key, Value>>,
  iteratee: Iteratee<Key, Value, [TransformedKey, TransformedValue]>,
) => fromEntries(entries(object).map(([key, value]) => iteratee([key, value])));
