import { entries } from './entries';
import { fromEntries } from './from-entries';

type Iteratee<
  Key extends string | number | symbol,
  Value,
  TransformedResult extends [string | number | symbol, unknown],
> = ([key, value]: [Key, Value]) => TransformedResult;

/**
 * Creates an object with entries generated by running each own enumerable entry of object through iteratee. The iteratee is invoked with a tuple argument: [key, value].
 * @param object The object to iterate over.
 * @param iteratee The function invoked per iteration.
 * @returns Returns the new mapped object.
 */
export const map = <
  Key extends string | number | symbol,
  Value,
  TransformedKey extends string | number | symbol,
  TransformedValue,
>(
  object: Readonly<Record<Key, Value>>,
  iteratee: Iteratee<Key, Value, [TransformedKey, TransformedValue]>,
) => fromEntries(entries(object).map(([key, value]) => iteratee([key, value])));
