AWSTemplateFormatVersion: 2010-09-09
Description: AWS Stack for ts-utils
# Metadata:

# Parameters:

# Mappings:

# Conditions:

Resources:
  DocumentationAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ts-utils-assets
      AccessControl: Private
      # PublicAccessBlockConfiguration:
      #   BlockPublicAcls: false
      #   BlockPublicPolicy: false
      #   IgnorePublicAcls: false
      #   RestrictPublicBuckets: false

  # DocumentationAssetsBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: DocumentationAssetsBucket
  #     PolicyDocument: {}

  DocumentationAssetsCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt
              - DocumentationAssetsBucket
              - DomainName
            Id: TsUtilsAssetsBucket
            S3OriginConfig: {}
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: TsUtilsAssetsBucket
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: allow-all
# Outputs:
