AWSTemplateFormatVersion: 2010-09-09
Description: AWS Stack for ts-utils
# Metadata:

# Parameters:

# Mappings:

# Conditions:

Resources:
  DocumentationAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ts-utils-assets
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  DocumentationAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DocumentationAssetsBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub
              - 'arn:aws:s3:::${Bucket}/*'
              - Bucket: !Ref DocumentationAssetsBucket

  DocumentationAssetsCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Origins:
          - DomainName: !GetAtt
              - DocumentationAssetsBucket
              - DomainName
            Id: TsUtilsAssetsBucket
            S3OriginConfig: {}
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: TsUtilsAssetsBucket
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: allow-all
# Outputs:
