AWSTemplateFormatVersion: 2010-09-09
Description: AWS Stack for ts-utils
# Metadata:

# Parameters:

# Mappings:

# Conditions:

Resources:
  DocumentationAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jergauth-ts-utils
      AccessControl: PublicRead
  DocumentationAssetsCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt
              - DocumentationAssetsBucket
              - DomainName
            Id: TsUtilsBucket
            S3OriginConfig: {}
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: TsUtilsBucket
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: allow-all
# Outputs:
