name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Library
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
